name: Push Docker Image


on:
    workflow_call:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: 'awesome-fastapi'


jobs:
  Push_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 

       # Extract metadata (tags, labels) for Docker
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
         images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      # Login against a Docker registry 
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Build Docker Image    
      - name: Build Docker Image
        run: |
         docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
         docker tag ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
 
          

      - name: Wait for Docker container to be ready
        run: sleep 30

      - name: Confirm Docker container is running
        run: docker ps

      # Push the Docker image to the registry
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
